# Logistic Regression Classifier

In [1]:
import pandas as pd

### Import data

In [2]:
data = pd.read_csv('../data_cleaning/preprocessed_train_2000_stopwords.csv')
# data = data[['text_lemmatized','sentiment']]
data = data.dropna()
data

Unnamed: 0                                               text  polarity  \
0              0  this is it for me y all im moving to another c...         0   
1              1  i want trump amp his family packing their sing...         0   
2              2  if you think of moving to another country in y...         0   
3              3  actually he will be moving to another country ...         0   
4              4  trump float the idea of moving to another coun...         0   
...          ...                                                ...       ...   
2033        2033  how about if this ungrateful pompous as quit h...         0   
2034        2034  people like this idiot hate america so much it...        -1   
2035        2035  i am never moving from california unless the d...        -1   
2036        2036  i really want to study abroad next year but it...         0   
2037        2037                                         empty line         0   

      subjectivity  
0               -1  
1               -1  
2               -1  
3               -1  
4               -1  
...            ...  
2033            -1  
2034             1  
2035             1  
2036            -1  
2037            -1  

[2034 rows x 4 columns]

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, f1_score, accuracy_score, confusion_matrix
from sklearn.metrics import roc_curve, auc, roc_auc_score
from sklearn.feature_extraction.text import TfidfVectorizer

import numpy as np
import nltk

## Subjectivity Detection

### Convert Text to TF-IDF

In [4]:
X_train = data['text']
y_train = data['subjectivity']

In [5]:
tfidf_vectorizer = TfidfVectorizer(use_idf=True)
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)

### Logistic Regression Classifier

In [6]:
lr_subj = LogisticRegression()
lr_subj.fit(X_train_tfidf,y_train)

LogisticRegression()

### Evaluate on 1000 evaluation dataset

In [7]:
test_cases = pd.read_csv('../data_cleaning/preprocessed_eval_1000_stopwords.csv')
test_cases

Unnamed: 0                                               text  polarity  \
0              0  just move to a completely different location i...         0   
1              1  i have started sharing information again about...         1   
2              2  my parent made the tough decision to move thei...        -1   
3              3  aye you all tryna head out it s too wild over ...         0   
4              4  when is val going to move to another country w...        -1   
...          ...                                                ...       ...   
1265        1265  in separation anxiety gavin bradley track the ...         1   
1266        1266  the crippling asian elder daughter feeling tha...         0   
1267        1267  wa on the phone with my dad last night and he ...        -1   
1268        1268  you may qualify to take advantage of two possi...         0   
1269        1269  kama par kama jale relocating to another count...         1   

      subjectivity  
0               -1  
1                1  
2                1  
3               -1  
4                1  
...            ...  
1265             1  
1266            -1  
1267             1  
1268            -1  
1269             1  

[1270 rows x 4 columns]

In [8]:
test_tfidf = tfidf_vectorizer.transform(test_cases['text'])
prediction_prob = lr_subj._predict_proba_lr(test_tfidf)[:,1]
prediction = lr_subj.predict(test_tfidf)

In [9]:
test_case_ground_truth = test_cases['subjectivity']
test_case_ground_truth = np.array(test_case_ground_truth)
test_case_ground_truth

array([-1,  1,  1, ...,  1, -1,  1], dtype=int64)

In [10]:
prediction

array([-1,  1,  1, ...,  1, -1,  1], dtype=int64)

In [11]:
print("Subjectivity Detection Model Evaluation")
print("1: OPINIONATED")
print("-1: NEUTRAL")
print(classification_report(test_case_ground_truth,prediction))
print('Confusion Matrix:\n',confusion_matrix(test_case_ground_truth, prediction))

Subjectivity Detection Model Evaluation
1: OPINIONATED
-1: NEUTRAL
              precision    recall  f1-score   support

          -1       0.70      0.64      0.67       608
           1       0.69      0.75      0.72       662

    accuracy                           0.70      1270
   macro avg       0.70      0.69      0.69      1270
weighted avg       0.70      0.70      0.70      1270

Confusion Matrix:
 [[388 220]
 [165 497]]


## Polarity Detection

In [12]:
data_polarity = data[data['polarity']!=0]
data_polarity

Unnamed: 0                                               text  polarity  \
5              5  i literally can t even shop alone and here i a...         1   
7              7  still cannot believe that i am moving into ano...        -1   
10            10  i am surprised a country called the u this is ...        -1   
11            11  i m honestly packing up my shit and moving to ...        -1   
12            12  when i went to work in germany for a year i we...         1   
...          ...                                                ...       ...   
2025        2025  yah man u wont go to another country to suppos...         1   
2028        2028  fuck you gabe kapler move to another country i...        -1   
2031        2031  a move to another country is looking better ev...         1   
2034        2034  people like this idiot hate america so much it...        -1   
2035        2035  i am never moving from california unless the d...        -1   

      subjectivity  
5                1  
7                1  
10               1  
11               1  
12               1  
...            ...  
2025             1  
2028             1  
2031             1  
2034             1  
2035             1  

[999 rows x 4 columns]

In [13]:
X_train = data_polarity['text']
y_train = data_polarity['polarity']

#### Convert data to TFIDF

In [14]:
tfidf_vectorizer = TfidfVectorizer(use_idf=True)
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)

### Logistic Regression Classifier

In [15]:
lr_pol = LogisticRegression()
lr_pol.fit(X_train_tfidf,y_train)


LogisticRegression()

#### Evaluate on 1000 evaluation dataset

In [16]:
test_cases = pd.read_csv('../data_cleaning/preprocessed_eval_1000_stopwords.csv')
test_cases = test_cases[test_cases['polarity']!=0]
test_cases

Unnamed: 0                                               text  polarity  \
1              1  i have started sharing information again about...         1   
2              2  my parent made the tough decision to move thei...        -1   
4              4  when is val going to move to another country w...        -1   
5              5  if you dont like it here then leave wow great ...        -1   
6              6  the new american dream is to move to another c...         1   
...          ...                                                ...       ...   
1260        1260  today might be my last day on linkedin premium...        -1   
1262        1262  im leaving twitter if elon buy it hold the sam...        -1   
1265        1265  in separation anxiety gavin bradley track the ...         1   
1267        1267  wa on the phone with my dad last night and he ...        -1   
1269        1269  kama par kama jale relocating to another count...         1   

      subjectivity  
1                1  
2                1  
4                1  
5                1  
6                1  
...            ...  
1260             1  
1262             1  
1265             1  
1267             1  
1269             1  

[662 rows x 4 columns]

In [17]:
test_tfidf = tfidf_vectorizer.transform(test_cases['text'])
prediction_prob = lr_pol._predict_proba_lr(test_tfidf)[:,1]
prediction = lr_pol.predict(test_tfidf)

In [18]:
test_case_ground_truth = test_cases['polarity']
test_case_ground_truth = np.array(test_case_ground_truth)
test_case_ground_truth

array([ 1, -1, -1, -1,  1, -1, -1, -1, -1, -1, -1,  1, -1, -1,  1, -1, -1,
        1, -1, -1, -1, -1, -1,  1,  1, -1, -1,  1, -1,  1,  1, -1,  1, -1,
       -1, -1, -1, -1, -1, -1,  1, -1,  1,  1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1,  1,  1, -1, -1, -1, -1, -1,  1, -1,  1, -1, -1,  1,
       -1, -1,  1, -1, -1, -1, -1, -1, -1, -1, -1,  1, -1, -1, -1, -1, -1,
       -1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1, -1, -1, -1, -1,
       -1,  1, -1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1, -1,
        1, -1, -1, -1,  1, -1, -1, -1, -1,  1,  1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1,  1,  1, -1, -1,  1, -1,  1, -1, -1, -1,  1,  1, -1, -1, -1, -1,
       -1, -1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        1,  1, -1, -1, -1, -1, -1, -1, -1,  1, -1, -1, -1, -1, -1, -1,  1,
       -1, -1, -1, -1, -1, -1,  1,  1, -1, -1, -1, -1, -1, -1,  1, -1, -1,
       -1, -1, -1, -1, -1

In [19]:
prediction

array([-1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1,  1, -1, -1,  1, -1,  1, -1, -1, -1,  1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1,  1, -1,  1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1,  1, -1, -1, -1, -1, -1, -1, -1,  1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1

In [20]:
print("Polarity Detection Model Evaluation")
print("1: POSITIVE")
print("-1: NEGATIVE")
print(classification_report(test_case_ground_truth,prediction))
print('Confusion Matrix:\n',confusion_matrix(test_case_ground_truth, prediction))

Polarity Detection Model Evaluation
1: POSITIVE
-1: NEGATIVE
              precision    recall  f1-score   support

          -1       0.77      0.94      0.85       449
           1       0.77      0.42      0.54       213

    accuracy                           0.77       662
   macro avg       0.77      0.68      0.70       662
weighted avg       0.77      0.77      0.75       662

Confusion Matrix:
 [[423  26]
 [124  89]]
